# Generated by Django 3.1.7 on 2022-07-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20220711_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
