# Generated by Django 3.1.7 on 2022-07-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_useraddress_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=4)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otpuser', to='crud.useraddress')),
            ],
        ),
    ]
