# Generated by Django 3.1.7 on 2022-07-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_temporaryotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=50, null=True)),
                ('name2', models.CharField(blank=True, max_length=50, null=True)),
                ('name3', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file')),
            ],
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='verify_email',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='verify_mobile',
        ),
        migrations.DeleteModel(
            name='TemporaryOTP',
        ),
    ]
